# Generated by Django 4.1 on 2022-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
